### ISSUE TITLE
Link provided by Paper doesn't work

### ISSUE THREAD

**Issue by jsebt** [aikar/timings#102]
When I do the /timings report command, paper gives me a link but the link doesn't exist
![image](https://user-images.githubusercontent.com/26907216/90822829-05352f00-e303-11ea-8130-47315fe3fc8c.png)

![image](https://user-images.githubusercontent.com/26907216/90822863-1120f100-e303-11ea-9c51-c00b21d78913.png)

I'm on Paper 1.6.1-136
Plugins (25): ActionHealth*, AuthMe, BannerMaker, Chunkmaster, DeadChest, dynmap*, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, ImageOnMap, LuckPerms, LWC, LWCTrust, OpenInv, PlugMan, ProtocolLib, SetHomes*, SinglePlayerSleep, SkinsRestorer, Timber, Vault, WorldEdit, WorldGuard

**Comment by electronicboy** [comment]
Replace /d= with /?id=, your control panel is janky and screwing up the output
