### ISSUE TITLE
Timings dont load

### ISSUE THREAD

**Issue by cloakfox** [aikar/timings#103]
New/fresh timings refuse to load: https://imgur.com/a/m0CjpFI

url: https://timings.aikar.co/?id=b2f7b57a73504e3991666a03539e3257

Been happening whole summer

Default timings config values in paper.yml

> timings:
  server-name: Foxcraft OneBlock
  enabled: true
  verbose: true
  server-name-privacy: true
  hidden-config-entries:
  - database
  - settings.bungeecord-addresses
  history-interval: 300
  history-length: 3600

**Comment by cloakfox** [comment]
Same issue still..
https://imgur.com/a/I0OR5Mj

**Comment by aikar** [comment]
you have too many plugins that's causing the data file to be too large.

Reduce your history-interval to like 2400 and should resolve it.
