### ISSUE TITLE
Aternos arghh!!

### ISSUE THREAD

**Issue by xmyoard** [aikar/timings#132]
I use aternos and it lags 
pls help argh!!
??
!?!?!

**Comment by benwoo1110** [comment]
lol

**Comment by xmyoard** [comment]
anyways>???>?>?

**Comment by benwoo1110** [comment]
You should contact aternos support then. Here is the wrong place.

**Comment by xmyoard** [comment]
ah argh!!

**Comment by electronicboy** [comment]
Please stop with the useless spam, I don't need it in my emails.
This issue tracker is for tracking issues with the timings website, not for support with timings themselves, please speak to your software vender or host for that.

**Comment by xmyoard** [comment]
ok topic changed, how to use timings then?

**Comment by electronicboy** [comment]
`/timings report` on most platforms, but, once again, ask your software vender for support, this is not the place for support with timings themselves.

**Comment by xmyoard** [comment]
then why did aikar created aikar/timings

**Comment by electronicboy** [comment]
This is the web UI, not the place for seeking support with actual timings.

**Comment by xmyoard** [comment]
then can you please say where can I get support for aikar/timings ?

**Comment by electronicboy** [comment]
you're not asking for support with aikar/timings, you're asking for support reading a timings report produced from the software you're using, which is compatible with and rendered with the timings UI whose source code lives here.

Once again, speak to your software vender for support; i.e. if you're using paper, ask paper, if you're using sponge, ask sponge

**Comment by xmyoard** [comment]
now this makes sense, thanks
