### ISSUE TITLE
Server-Crash - ArrayIndexOutOfBoundsException "co.aikar.timings.TimingHistory"

### ISSUE THREAD

**Issue by RedstoneFuture** [aikar/timings#156]
Hello. I would like to report the following crash to find a possible error in the timing system. It is also possible that it is a chunk error - I don't know for sure.

The error occurred on a production server, which prevents me from giving out all the information. But here hopefully all the necessary info from the crash report: https://bytebin.lucko.me/iRnRthuwRY

If you have any questions, I will respond in a timely manner. So far, the error has occurred only once.

**Comment by electronicboy** [comment]
Wrong repo for such reports, and not generally an issue with timings or paper, something corrupted your servers state (generally unsafe async access to internals)

**Comment by RedstoneFuture** [comment]
Ok, thanks.
