### ISSUE TITLE
Timings report tells me a task run by a class is causing lag, but I don't know which task

### ISSUE THREAD

**Issue by Miclebrick** [aikar/timings#42]
A picture is worth a thousand words: 
![image](https://user-images.githubusercontent.com/6323125/34423508-73e8311c-ebea-11e7-8b24-9ee1cdbb6d4d.png)

and here's my pipes class file https://pastebin.com/FURybDUM

I would really like to know which one is causing the lag. I do have a hunch - maybe pipes putting items into furnaces is causing it to tick the furnace tile entity???

**Comment by Miclebrick** [comment]
aha - I figured out how to use paper timings things and now:
http://prntscr.com/hts6id
    private static void addAndRemove(Inventory inventory, Inventory oldInventory, ItemStack fullItem) {
        try (Timing timed = Timings.ofStart(Erudition.getInstance(), "Pipe Sync End Task")) {
            if (inventory.getType() == InventoryType.HOPPER) {
                Hopper hopper = (Hopper) inventory.getHolder();
                BlockFace facing = ((Directional) hopper.getData()).getFacing();
                Material type = hopper.getBlock().getRelative(facing).getType();
                if (type.name().contains("GLASS")) {
                    async(() -> PipeManager
                            .pipeTick(hopper.getLocation(), fullItem, facing, 0, oldInventory,
                                      System.currentTimeMillis()));
                    return;
                }
            }
            ItemStack item = fullItem.getAmount() == 1 ? fullItem : fullItem.clone();
            item.setAmount(1);
            while (!oldInventory.getLocation().equals(inventory.getLocation())
                    && ItemUtils.canFit(inventory, item)
                    && ItemUtils.getTotalItems(oldInventory, item) >= item.getAmount()) {
                ItemUtils.removeInventoryItems(oldInventory, item);
                ItemUtils.addToInventory(inventory, item);
            }
        }
    }

**Comment by aikar** [comment]
It's likely in the ItemUtils last lines - but please join my discord or paper irc for discussion/help - issues isnt really place for it.

https://aikarchat.emc.gs for IRC
https://aikardiscord.emc.gs for Discord
