### ISSUE TITLE
Tree mode view / hierarchical view mode

### ISSUE THREAD

**Issue by bergerkiller** [aikar/timings#44]
I've added many custom timings to TrainCarts to help in detecting performance issues. Without it, all people see is that EntityMinecart has a lot of tick time. It works wonderfully - the only problem is that the timings viewer offers no hierarchical view.

What I mean by that is that there is no parent-child relationship possible where children run in the timeslice of the parent. This sort of information would probably have to be stored in the timings reports themselves. If it has to be added to the library that generates the report and called manually specifying the parent timings node, that'd be fine with me too.

For example:
![Image of timings report](https://i.imgur.com/mLvzaKM.png)

What I'd like to see (mockup, not complete)
![Mockup](https://i.imgur.com/xGNzTJ2.png)

I've named the entries like A - B - C so that the hierarchy is clear, but it lacks native support unfortunately. I'd love to see some form of tree hierarchical view with 'Train Physics', under it 'MinecartMember::onPhysicsPostMove()' with under that node a couple like 'onMove()' and 'MEMBER_MOVE'. Right now it seems as if the plugin is using huge amounts of tick time if you were to tally the numbers.

Having it hierarchical would also clean up the view itself.

**Comment by aikar** [comment]
You are using an unsupported old version of timings.

This repo is only for Timings v2. Please move to using [Paper](https://paper.emc.gs) and you will get exactly what you are looking for.
https://timings.aikar.co

For making your plugin support multiple Timings versions, please see: https://github.com/aikar/minecraft-timings

For an example of implementation, please see: 
https://github.com/aikar/commands/blob/master/bukkit/src/main/java/co/aikar/commands/BukkitCommandManager.java#L88
https://github.com/aikar/commands/blob/master/bukkit/src/main/java/co/aikar/commands/BukkitRegisteredCommand.java

**Comment by bergerkiller** [comment]
Yeah I was already using minecraft-timings under the hood, so I'm quite excited now! :)

Does using minecraft-timings mean it does this tree view display automatically? Or should I build something specific for Paper timings to have it work? I'll play a bit with the Paperspigot server to see what kind of timings reports are created.

**Comment by aikar** [comment]
@bergerkiller if you register multiple timings, then yes v2 does collect it in a way that the v2 ui shows it as seen in the test data.

v2 does not handle recursive timings is all

ie:
foo > bar > baz > foo > bar > baz 

timings will only attribute to the first depth levels, you can't see a foo under a foo.

Your end users will need to run paper to get the better timings reports.

V1 will show it linearly.

**Comment by bergerkiller** [comment]
Currently what I'm getting in the report isn't exactly what I expected: https://timings.aikar.co/?id=b56e10ea75ba4bb189e1c7a3c6923b0e

It might have to do with how I create the timings though. Currently what it does is create MCTiming instances like so:

`TimingManager.of(plugin).of(getTimingName(plugin, name));`

Where the name is calculated like so:
```
    private static String getTimingName(Plugin plugin, String name) {
        return String.format("Plugin: %s v%s Event: %s", 
                plugin.getName(),
                plugin.getDescription().getVersion(),
                name);
}
```

But I suspect this format is abusing v1 timings mechanics to have plugin timings, and maybe it doesn't work for v2 timings? As for name, its formatted like you saw in the v1 report:
`Node A - Node B - Node C`

Got advice?

**Comment by bergerkiller** [comment]
Alright removing that made the view look almost perfect. I only have to magic away the names for paper so it doesnt become so long, but other than that, its good. Thanks for creating such a powerful timings library and service :)

![Output](https://puu.sh/zfQNz/5ac910c9f2.jpg)

**Comment by aikar** [comment]
Agreed, and now I look at it I guess it's not a big deal to make a manager each time. I was thinking it would cause a lookup on which timing provider to use, but it appears I am storing that statically.
