### ISSUE TITLE
Where can I view V1 timing report?

### ISSUE THREAD

**Issue by cnwillz** [aikar/timings#47]
Seems current version Timing viewer don't support the old version V1 timing report, yet I have some server still using 1.7.10 MCPC server, they only give me V1 timing report. How can I do or where can I find a lagacy Timing viewer repo.

**Comment by aikar** [comment]
https://www.spigotmc.org/resources/timingspatch-fix-the-timings-command.29217/

Please use that plugin to update the V1 to use md5's server.
