### ISSUE TITLE
Reports not showing.

### ISSUE THREAD

**Issue by Rsslone** [aikar/timings#56]
My timing reports keep coming up as "Oops - Could not load Timings Report". I've check the URL several times and I've used this tool many times, I think something is wrong.
https://timings.aikar.co/?id=12c033a4700746d4a499b25bae6ce978

**Comment by aikar** [comment]
What is your timings settings for history and interval? It appears the file is too large and unable to be loaded :/

Try using 300 for interval and 3600 for history length for best results

**Comment by Rsslone** [comment]
Okay that makes sense. I'll change my settings accordingly. Thank you.

**Comment by aikar** [comment]
I recently updated PHP and it appears the update now makes PHP use more memory  - so I have been having problems with larger reports loading, but I can't really raise my memory limits higher, just going to need servers to use less resource intensive settings.

**Comment by Rsslone** [comment]
Ouch. I poked around with web development before so I can understand that. Maybe have sponge change their max settings. I know their max settings now is 14400 for the length, at least at 180 interval.

**Comment by aikar** [comment]
It does not appear they have changed the defaults:
https://github.com/SpongePowered/SpongeCommon/blob/a9423c7ec9f2b423b52c273f7e7a23818a8f3e41/src/main/java/org/spongepowered/common/config/category/TimingsCategory.java#L47
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/config/category/TimingsCategory.java

Still shows 300/3600

**Comment by Rsslone** [comment]
That's default, but you can turn it up, as i've done. They have a hard limit, im not sure how it calculates it but when I turned my history length up it said the max was 14400 at 180 interval, or I could turn my interval way up and achieve a higher history.
