### ISSUE TITLE
timings paste in console

### ISSUE THREAD

**Issue by Cobwebster** [aikar/timings#67]
There seems to be a issue with grabbing a timings report from console, if I run "timings paste" in multicraft/any console it prints this link

https://timings.aikar.co/d=2b7c548f0d114599adaf84049ca8e4e7

which doesn't seem to work. Works in-game, like the link I get in-game is somehow different and works. But the one processed by console fails.

**Comment by aikar** [comment]
it's caused by your panel or log system breaking the link. if you change the /d to /?id it will work:

https://timings.aikar.co/?id=2b7c548f0d114599adaf84049ca8e4e7

Need to report this to your panel.
