### ISSUE TITLE
Incorrect counts for expanded subsections

### ISSUE THREAD

**Issue by froobynooby** [aikar/timings#86]
**I believe this is related to https://github.com/PaperMC/Paper/issues/2489 (see my comment there)**

When you expand a section in the timings tab, the counts of the subsections are lower than they should be. For example, I took a [10 minute report](https://timings.aikar.co/?id=723211e10c0541109424d788fde1f42c) in an empty world with a single player:
<img width="931" alt="65835602-c9c8f500-e32b-11e9-8d87-3c16f47a8ce4" src="https://user-images.githubusercontent.com/4980841/73135628-c0f2f080-408b-11ea-97b5-9463c93efaa6.PNG">
In this image, a 12000 tick window is highlighted. "Minecraft::world - entityTick" has a count of 12000, which is correct, however the subsection "Minecraft::tickEntity - nms.EntityPlayer" has a count of 6000, which is incorrect.

If you choose an 18000 tick window, any subsection has a count of 12000; for a 24000 tick window, any subsection has a count of 18000; etc. It's always 6000 ticks fewer than it should be. This only seems to affect the first layer down, i.e. subsections of subsections are fine.

**Comment by aikar** [comment]
this is now fixed https://github.com/aikar/timings/commit/f05a67fec9f0bed059b9395628e6902ea22944b4
