### ISSUE TITLE
NPE on missin group ids \ Or maybe i am doing something very wrong :D

### ISSUE THREAD

**Issue by evernife** [aikar/timings#94]
I am applying a more verbose way for timings, in case, show the specific location of tiles and its lag.

The point is, dependending on the server there are too many tiles of specific type, that is the why i need to "filter" them based on its cost.

That is something i already did.

But, when i filter them the site will get a NPE when some ids are being rendered.

What should i do?
Is there a way to remove them from the report?

Actually i am removing the ones i do not want at this point, using a `continue;`
https://github.com/PaperMC/Paper/blob/master/Spigot-API-Patches/0004-Timings-v2.patch#L1853

Here are two timings:

More verbose Tiles: https://timings.aikar.co/?id=3535610d3f944b7ea3f1cd64f67c684e
More verbose Tiles with NPE: https://timings.aikar.co/?id=1647d88641d7472692c73df3c63e6ec8

**Comment by aikar** [comment]
Please do not do this. This will cause an enormous amount of timing entries that will bloat the report. I am going to try to handle this sometime in the future.

Use the regions tab to find quantity of tiles to identify areas to investigate.
